Refactor GitHub Actions workflow for deployment: rename job, add file existence check for index.html

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,13 +17,17 @@ concurrency:
     cancel-in-progress: false
 
 jobs:
-    build-and-deploy:
+    deploy:
         runs-on: ubuntu-latest
-        environment:
-            name: github-pages
-            url: ${{ steps.deployment.outputs.page_url }}
         steps:
             - uses: actions/checkout@v3
+            
+            - name: Check files
+              run: |
+                if [ ! -f "index.html" ]; then
+                  echo "::error::index.html not found"
+                  exit 1
+                fi
             
             - name: Setup Pages
               uses: actions/configure-pages@v3
@@ -34,5 +38,4 @@ jobs:
                 path: '.'
                 
             - name: Deploy to GitHub Pages
-              id: deployment
               uses: actions/deploy-pages@v2
